// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config')

// Plugins.
const CopyWebpackPlugin        = require('copy-webpack-plugin')
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts')

// Utilities.
const path       = require('node:path')
const imagesPath = path.resolve(__dirname, './assets/images')
const fontsPath  = path.resolve(__dirname, './assets/fonts')

// Entry Points.
const entryPoints = {
  // Main stylesheet.
  'css/main': path.resolve(__dirname, './dev/scss', 'main.scss'),

  // Fonts Stylesheet.
  'css/fonts': path.resolve(__dirname, './dev/scss', 'fonts.scss'),

  // Editor styles.
  'css/editor-styles': path.resolve(
    __dirname,
    './dev/scss',
    'editor-styles.scss',
  ),

  // Customizer styles.
  'css/customizer': path.resolve(__dirname, './dev/scss', 'customizer.scss'),

  // Editor JS.
  'js/rev-editor': path.resolve(__dirname, './dev/js/editor', 'rev-editor.js'),

  // Custom Frontend JS.
  'js/rev-frontend': path.resolve(
    __dirname,
    './dev/js/frontend',
    'rev-frontend.js',
  ),

  // Elementor JS.
  'js/rev-elementor': path.resolve(
    __dirname,
    './dev/js/elementor',
    'rev-elementor.js',
  ),

  // Customizer JS.
  'js/rev-customizer': path.resolve(
    __dirname,
    './dev/js/customizer',
    'rev-customizer.js',
  ),
}

module.exports = {
  ...defaultConfig,
  ...{
    entry: entryPoints,
    output: {
      ...defaultConfig.output,
      path: path.resolve(__dirname, './assets'),
      chunkFilename: 'js/[name].js',
      clean: false,
    },
    plugins: [
      ...defaultConfig.plugins,

      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, './dev/images'),
            to: imagesPath,
          },
          {
            from: path.resolve(__dirname, './dev/fonts'),
            to: fontsPath,
          },
        ],
      }),

      // Remove empty `.js` files generated by webpack.
      // Intentionally set to AFTER WP generates its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
      }),
    ],
  },
}
